apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      name: helloworld
      labels:
        app: helloworld
    spec:
      containers:
      - image: 17051998/nguyenbanh123-jvm
        name: quarkus
        ports:
          - name: helloworld
            containerPort: 8089
            protocol: TCP
        imagePullPolicy: Always
        env:
          - name: "GREETING_MESSAGE"
            valueFrom:
            configMapKeyRef:
              key: "greeting"
              name: "hello-config"