apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-2
  name: helloworld-2
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8089
  selector:
    app: helloworld-2
  sessionAffinity: None
